bookers2/config/routes.rb
Rails.application.routes.draw do
  get '/search' => "searchs#search"
  post 'follow/:id' => 'relationships#follow', as: 'follow'
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow'
  get 'follower/:id' => 'relationships#follower', as: 'follower'
  get 'followed/:id' => 'relationships#followed', as: 'followed'
  get 'favorites/create'
  get 'favorites/destroy'
  root 'homes#top'
  get 'home/about' => 'homes#about'
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
    resource :favorites,only: [:create, :destroy]
    resources :book_comments,only: [:create, :destroy]
  end
end

bookers2/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
  has_many :favorites,dependent: :destroy
  has_many :book_comments,dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id:user.id).exists?
	end
end

bookers2/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit]

  def show
    @booker = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @follow = User.find(params[:id])
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
      @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    unless @user == current_user
      redirect_to books_path
    end
  end
end

bookers2/app/helpers/books_helper.rb
module BooksHelper
end

bookers2/app/views/books/_form.html.erb
<%= form_with model: book, local: true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

bookers2/app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <% if book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(book),method: :delete do %>
              ❤︎<%= book.favorites.count %>
            <% end %>
          </td>
        <% else %>
          <td>
            <%= link_to book_favorites_path(book),method: :post do %>
              ♡<%= book.favorites.count %>
            <% end %>
          </td>
        <% end %>
          <td>
            コメント数:<%= book.book_comments.count %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

bookers2/app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
  		<%= render 'form', book: @book %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

bookers2/app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <%= render "layouts/errors", obj: @book %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'index', books: @books%>
    </div>
  </div>
</div>

bookers2/app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <% unless current_user == @follow %>
        <% if current_user.following?(@follow) %>
          <%= link_to 'フォロー外す', unfollow_path(@follow.id), method: :POST, class: "btn btn-success" %>
        <% else %>
          <%= link_to 'フォローする', follow_path(@follow.id), method: :POST, class: "btn btn-success" %>
        <% end %>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @booker %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td>
  		      <%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <% if @book.favorited_by?(current_user) %>
          <td>
            <%= link_to book_favorites_path(@book),method: :delete do %>
              ❤︎<%= @book.favorites.count %>
            <% end %>
          </td>
          <% else %>
          <td>
            <%= link_to book_favorites_path(@book),method: :psot do %>
              ♡<%= @book.favorites.count %>
            <% end %>
          </td>
          <% end %>
          <td>コメント数:<%= @book.book_comments.count %></td>
          <% if @book.user == current_user %>
          <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
          <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <% @book.book_comments.each do |book_comment| %>
      <table>
        <tr>
          <td>
          <%= link_to user_path(book_comment.user) do %>
          <%= attachment_image_tag(book_comment.user, :profile_image, :fill,100,100, fallback: "no-image-icon.jpg") %><br>
          <%= book_comment.user.name %>
          <% end %>
          </td>
          <td><%= book_comment.comment %></td>
          <% if book_comment.user == current_user %>
          <td><%= link_to "destroy", book_book_comment_path(@book, book_comment.id), method: :delete, class: "btn btn-sm btn-danger" %></td>
          <% end %>
        </tr>
      </table>
      <% end %>
      <div>
        <%= form_with model: [@book, @book_comment], local: true do |f| %>
          <% if @error_comment.present? %>
          <div id="error_explanation">
            <h2><%= @error_comment.errors.count %>prohibited this obj from being saved:</h2>
            <ul>
            <% @error_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
          <% end %>
          <%= f.text_area  :comment, size: "90" %>
          <div>
            <%= f.submit "送信" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>